### ISSUE TITLE
Removing node_modules

### ISSUE THREAD

**Issue by abdounasser202** [jessicaNono/correcttel#7]
First, GOOD JOB, this library will help

Now, I'm wondering:

1. If dependencies are already in package.json file, why node_modules folder is pushed ? It's not better to not push it ?
2. I also saw that the versions in the dependencies are ^x.y.z (x.y.z are version number), it's not better to fix the version like ==x.y.z to make sure there won't be any backward compatibility with your package if any of these dependencies has new releases ?

**Comment by jessicaNono** [comment]
Hello Nasser, 
Thank youuu, I will remove the node_modules from the repo.  For the version, we will check if we need to make it like ==x.y.z.
